.TH ft_select 1 "June 08, 2017" 42
.SH NAME
.B ft_select
\-- allows you to choose from a selection of arguments
.SH SYNOPSIS
.B ./ft_select
[arg...]
.br
<command>
.B `./ft_select
[arg...]`
.SH DESCRIPTION
.B ft_select
arguments are displayed onscreen; once selected
.B ft_select
will print selections to the standard output separated by a single space
.
.PP
.RE
.RS 5
.B Controls:
.br
.RS 2
.br
Arrows             |   Move cursor
.br
Space              |   Select current argument
.br
Del / Backspace    |   Remove argument from display
.br
Enter              |   Print current selections to stdout
.br
Esc                |   Disregard selection and exit
.br
Alt+C              |   Access colors menu
.SH AUTHOR
jpfeffer jpfeffer@student.42.us.org